from . import purchase_inherit_revision
from . import project_inherit_location
from . import production_inherit
from . import stock_line_inherit
from . import stock_quantity_inherit
from . import bom_inherit
from . import crm_inherit
from . import quotation_estimate
from . import estimate_masters
