# -*- coding: utf-8 -*-
# Part of BrowseInfo. See LICENSE file for full copyright and licensing details.

{

    "name": "Daisy Hospital",
    "version": "14.0.0.1",
    "currency": 'INR',
    "summary": "Daisy Hospital Management System",
    "category": "Industries",
    "description": """
    This module is used to manage Hospital and Healthcare Management and Clinic Management apps. 
""",

    "depends": ["base", "sale_management", "stock", "account","mail",'website'],
    "data": [
        
        'views/assets.xml',
        'views/test_view.xml',
        
        'views/labscan.xml',
        'views/file_room.xml',
        'views/discharge.xml',
        'views/scan_test.xml',
        'report/diet_plan.xml',
        'report/header.xml',
        'report/discharge.xml',
        'report/in_patient_bill.xml',
        'report/in_patient.xml',
        'report/lab_bill.xml',
        'report/scan_bill.xml',
        'report/prescription_bill.xml',
        'report/registration_bill.xml',
        'views/set_fruits.xml',
        'views/set_veg.xml',
        'views/picking_inherit.xml',
        'security/doctor_access.xml',
        'views/set_protein.xml',
        'views/set_rice.xml',
        'report/bills_report.xml',
        'views/login_page.xml',
        'views/main_menu_file.xml',
        'wizard/medical_appointments_invoice_wizard.xml',
        'wizard/create_prescription_invoice_wizard.xml',
        'wizard/create_prescription_shipment_wizard.xml',
        'wizard/whatsapp_wizard.xml',
        'views/medical_medicament.xml',
        'views/medical_drug_route.xml',
        'wizard/medical_lab_test_create_wizard.xml',
        'wizard/medical_lab_test_invoice_wizard.xml',
        'views/medical_prescription_order.xml',
        'views/medical_directions.xml',
        'views/medical_dose_unit.xml',
        'views/medical_patient_evaluation.xml',
        'views/medical_family_disease.xml',
        'views/medical_inpatient_registration.xml',
        'views/medical_inpatient_medication.xml',
        'views/medical_insurance_plan.xml',
        'views/medical_appointment.xml',
        'views/medical_insurance.xml',
        'views/medical_patient_lab_test.xml',
        'views/medical_lab_test_units.xml',
        'views/medical_lab.xml',
        'views/medical_feedback.xml',
        'views/medical_neomatal_apgar.xml',
        'views/medical_pathology_category.xml',
        'views/medical_pathology_group.xml',
        'views/medical_pathology.xml',
        'views/medical_patient_disease.xml',
        'views/medical_patient_medication.xml',
        'views/medical_patient_medication1.xml',
        'views/medical_patient_pregnancy.xml',
        'views/medical_patient_prental_evolution.xml',
        'views/medical_patient.xml',
        'views/medical_physician.xml',
        'views/medical_preinatal.xml',
        'views/medical_prescription_line.xml',
        'views/medical_puerperium_monitor.xml',
        'views/medical_rcri.xml',
        'views/medical_rounding_procedure.xml',
        'views/medical_test_critearea.xml',
        'views/medical_test_type.xml',
        'views/medical_vaccination.xml',
        'views/res_partner.xml',
        'views/medical_doctor.xml', 
        'report/report_view.xml',
        'report/appointment_recipts_report_template.xml',
        'report/medical_view_report_document_lab.xml',
        'report/medical_view_report_lab_result_demo_report.xml',
        'report/newborn_card_report.xml',
        'report/patient_card_report.xml',
        'report/patient_diseases_document_report.xml',
        'report/patient_medications_document_report.xml',
        'report/patient_vaccinations_document_report.xml',
        'report/prescription_demo_report.xml',
        'report/patient_ebook.xml',
        'report/doctor_ebook_diet.xml',
        'report/doctor_ebook.xml',
        'report/doctor_ebook_lab.xml',
        'report/doctor_ebook_scan.xml',
        'report/doctor_ebook_pres.xml',
        'report/doctor_ebook_exercise.xml',
        'report/diet_report.xml',
        'views/diet_for.xml',
        'views/set_diets.xml',
        'views/medical_habit.xml',
        'views/patient_document.xml',
        'views/medical_document.xml',
        'views/prescribe_diet.xml',
        'views/test_unit.xml',
        'views/medical_symptoms.xml',
        'views/res_city.xml',
        'views/treatment_for.xml',
        'views/register_payment.xml',
        'views/float.xml',
        'wizard/register_wizard.xml',
        'views/patient_bills.xml',
        'views/account_payment_inherit.xml',
        'views/product_product.xml',
        'report/reg_barcode.xml',
        'report/file_room.xml',
        'report/file_barcode.xml',
        'report/patient_ebook_format.xml',
        'report/appointment_qrcode.xml',
        'views/web_page.xml',
        'security/company_access.xml',
        'security/reception_access.xml',
        'security/hospital_groups.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'security/doctor_access.xml',
    ],
    "author": "Abith",
    "website": "https://www.facebook.com/abith.raj",
    "installable": True,
    "application": True,
    "auto_install": False,
    "images": ["static/description/Banner.png"],
    "live_test_url": 'https://youtu.be/fk9dY53I9ow',

}

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
