# -*- coding: utf-8 -*-
{
	'name': 'HR Model',
	'version': '12.0.1.0.0',
	'summary': 'Record Model Information',
	'category': 'Tools',
	'author': 'odoo',
	'maintainer': 'odoo developer',
	'company': 'odoo Model',
	'website': ' ',
	'depends': ['base','hr','hr_recruitment','crm',
	'sale','sale_management','sales_team','sale_timesheet','hr_payroll','hr_attendance','account','contacts','hr_holidays'],
	'data': [

'views/task_extend.xml',
'views/journal_extend.xml',
'views/bank_statement.xml',
'views/bloodgroup.xml',
'views/attendance_extend.xml',
 'views/hrapp.xml',
  'views/project_extend.xml',
   'views/leave_extend.xml',
   'views/loan.xml',
# 'views/lead.xml',
# 'views/sale.xml',
'views/pay.xml',
'views/leave_tree.xml',
'views/leave_access.xml',
'views/accessrights.xml',
'views/taskrights.xml',
'views/invoice_report.xml',
'views/account_extend.xml',
'views/sale_extend.xml',
'reports/payslip.xml',
'reports/payslipnew.xml',
'views/approve_description.xml',
'views/refuse_description.xml',
'views/accountbankstatementline.xml',

'views/sale_report.xml',
'views/recruitment.xml',
'views/hrshortlist.xml',
'views/afterinterview.xml',
'views/hrafterinterview.xml',
'security/ir.model.access.csv',
'security/security.xml'


	],
	'images': [],
	'license': 'AGPL-3',
	'installable': True,
	'application': False,
	'auto_install': False,
}
