{
    'name': "Silliconz",
    'description': "",
    'version': "19.0.1.0.0",
    'depends': ['base', 'purchase', 'stock', 'project', 'mrp', 'crm', 'sale', 'account','mail', 'sale_crm', 'hr', 'report_xlsx'],
    'author': "BWS",
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',  
        "data/sequence.xml",
        "data/mail_template.xml",
        # "data/sale_order_mail_inherit.xml",
        "data/sale_order_mail.xml",
        'views/enquiry_type_views.xml',
        'views/vendor_application.xml',
        'views/crm_lead_views.xml',
        'views/sale_order_inherit.xml', 
        'views/purchase_order.xml',
        'views/terms_condition_type.xml',
        'views/purchase_report_inherit.xml',
        'views/sale_report_inherit.xml',
        "views/material_request_view.xml",
        "views/res_partner.xml",
        "views/transporter_master_views.xml",
        "views/stock_picking_view.xml",
        "views/mrp_production.xml",
        "views/stock_location_enable.xml",
        "views/purchase_order_request.xml",
        "views/product_template_inherit.xml",
        "views/hr_employee_view.xml",
        "views/account_move.xml",
        "views/user_setting.xml",
        "views/customer_application_views.xml",
        'wizards/submit_lvl2_wizard.xml',
        'wizards/reject_level1.xml',
        "wizards/purchase_request_wizard.xml",
        "wizards/create_transfer_wizard.xml",
        "wizards/create_po_wizard.xml",
        "wizards/purchase_order_moq_wizard.xml",
        "wizards/account_bill_validation.xml",
        "wizards/atp_report_wizard.xml",
        "wizards/bom_report_wizard.xml",
        "reports/atp_report_pdf.xml",
        "reports/purchase_report_inherit.xml",
        "reports/pdf_reports.xml",
        "reports/purchase_request_report.xml",
        "reports/bom_report_template.xml",
        "reports/material_request_report.xml",
        "reports/sale_order_report_inherit.xml",
        "views/menus.xml",
    ],
    'assets': {
        # 'web.report_assets_pdf': [
        #     'silliconz_module/static/src/img/iso.jpg',
        # ],
    },
    'application': True,
    'license': 'LGPL-3',
}
