{
    "name": "Odoo Tally Connector",
    "version": "1.0",
    "author": "Abith Raj",
    "summary": "Custom connector to sync Odoo with Tally",
    "description": "Send and receive data (Ledger, Invoice, Bills) between Odoo and Tally",
    "category": "Accounting",
    "depends": ["base", "account"],
    "data": [
        "security/ir.model.access.csv",
        "reports/ledger_template.xml",
        "reports/tally_xml_reports.xml",
        "wizards/tally_menus.xml",
        "wizards/tally_ledger.xml",
        "wizards/tally_invoice.xml",
        "wizards/tally_bill.xml",
        "wizards/import_export.xml",
        "views/tally_config_views.xml",
        "views/tally_partner_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
